const SHEET_CSV_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vT8yHpEmpNIWvi6FIo1ntB-tG_xjze0EE297G94Hp37vIsCH3QntRiUOo39_B5Ocg/pub?gid=1610754135&single=true&output=csv";
// 新しい「更新履歴」「サイト情報」シートを公開した後、gidをここへ入れてください。
const HISTORY_SHEET_GID="";
const SITE_INFO_SHEET_GID="";
const PUBLISHED_SHEET_BASE="https://docs.google.com/spreadsheets/d/e/2PACX-1vT8yHpEmpNIWvi6FIo1ntB-tG_xjze0EE297G94Hp37vIsCH3QntRiUOo39_B5Ocg/pub";

const memberEmoji={timelesz:"🕰️","佐藤勝利":"❤️","菊池風磨":"💜","松島聡":"💚","寺西拓人":"🩵","原嘉孝":"🎽","橋本将生":"🩷","猪俣周杜":"💛","篠塚大輝":"🤍"};
const memberOrder=["timelesz","佐藤勝利","菊池風磨","松島聡","寺西拓人","原嘉孝","橋本将生","猪俣周杜","篠塚大輝"];
const birthdays={"佐藤勝利":{year:1996,color:"red"},"菊池風磨":{year:1995,color:"purple"},"松島聡":{year:1997,color:"green"},"寺西拓人":{year:1994,color:"blue"},"原嘉孝":{year:1995,color:"lime"},"橋本将生":{year:1999,color:"pink"},"猪俣周杜":{year:2001,color:"yellow"},"篠塚大輝":{year:2002,color:"white"}};
const categories={TV:{label:"TV",icon:"monitor"},RADIO:{label:"RADIO",icon:"radio"},MAGAZINE:{label:"MAGAZINE",icon:"book"},CONCERT:{label:"CONCERT",icon:"mic"},EVENT:{label:"EVENT",icon:"ticket"},RELEASE:{label:"RELEASE",icon:"disc"},MOVIE:{label:"MOVIE",icon:"movie"},BIRTHDAY:{label:"BIRTHDAY",icon:"cake"},YOUTUBE:{label:"YOUTUBE",icon:"play"}};
const iconPaths={search:'<circle cx="11" cy="11" r="7"></circle><path d="m20 20-3.5-3.5"></path>',monitor:'<rect x="3" y="5" width="18" height="13" rx="2"></rect><path d="M8 21h8"></path>',radio:'<rect x="3" y="7" width="18" height="12" rx="2"></rect><path d="m7 7 10-4"></path><circle cx="8" cy="13" r="2"></circle><path d="M13 12h5M13 15h5"></path>',book:'<path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H11v16H6.5A2.5 2.5 0 0 0 4 21.5z"></path><path d="M20 5.5A2.5 2.5 0 0 0 17.5 3H13v16h4.5A2.5 2.5 0 0 1 20 21.5z"></path>',mic:'<rect x="9" y="2" width="6" height="12" rx="3"></rect><path d="M5 10a7 7 0 0 0 14 0M12 17v5M8 22h8"></path>',ticket:'<path d="M3 8a2 2 0 0 0 2-2h14a2 2 0 0 0 2 2v8a2 2 0 0 0-2 2H5a2 2 0 0 0-2-2z"></path><path d="M13 6v12"></path>',disc:'<circle cx="12" cy="12" r="9"></circle><circle cx="12" cy="12" r="2"></circle>',movie:'<rect x="3" y="6" width="18" height="14" rx="2"></rect><path d="m7 6 2-3M12 6l2-3M17 6l2-3"></path>',cake:'<path d="M4 10h16v10H4z"></path><path d="M8 10V7M12 10V6M16 10V7"></path><path d="M6 14c1.5 1 2.5 1 4 0 1.5 1 2.5 1 4 0 1.5 1 2.5 1 4 0"></path>',play:'<path d="m8 5 11 7-11 7z"></path>',clock:'<circle cx="12" cy="12" r="9"></circle><path d="M12 7v5l3 2"></path>',pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0z"></path><circle cx="12" cy="10" r="2"></circle>',link:'<path d="M10 13a5 5 0 0 0 7.1.1l2-2a5 5 0 0 0-7.1-7.1l-1.1 1.1"></path><path d="M14 11a5 5 0 0 0-7.1-.1l-2 2A5 5 0 0 0 12 20l1.1-1.1"></path>',"chevron-left":'<path d="m15 18-6-6 6-6"></path>',"chevron-right":'<path d="m9 18 6-6-6-6"></path>',x:'<path d="M18 6 6 18M6 6l12 12"></path>',layers:'<path d="m12 2 9 5-9 5-9-5z"></path><path d="m3 12 9 5 9-5M3 17l9 5 9-5"></path>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"></rect><path d="M16 3v4M8 3v4M3 10h18"></path>',history:'<path d="M3 12a9 9 0 1 0 3-6.7L3 8"></path><path d="M3 3v5h5M12 7v5l3 2"></path>',"share-2":'<circle cx="18" cy="5" r="3"></circle><circle cx="6" cy="12" r="3"></circle><circle cx="18" cy="19" r="3"></circle><path d="m8.6 13.5 6.8 4M15.4 6.5l-6.8 4"></path>'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${iconPaths[name]||""}</svg>`;
document.querySelectorAll("[data-icon]").forEach(el=>el.innerHTML=icon(el.dataset.icon));
const $=id=>document.getElementById(id);
let events=[],shownMonth=new Date(2026,6,1),selectedMember=localStorage.getItem("timeleszSelectedMember")||"ALL",selectedCategory="ALL",searchText="";
const now=new Date();let selectedDate=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;
const fallbackHistory=[{version:"Ver.1.9.1",date:"2026.7.15",changes:["カレンダー内のメンカラ絵文字を左寄せ・下詰めに調整","共有メニューと年月移動画面を調整"]},{version:"Ver.1.9",date:"2026.7.15",changes:["共有機能を追加","年月ジャンプを追加"]},{version:"Ver.1.8",date:"2026.7.13",changes:["誕生日表示を追加","メンバー絞り込みを改善"]},{version:"Ver.1.7",date:"2026.7.12",changes:["Googleスプレッドシート連携"]}];
const fallbackSiteInfo={version:"Ver.1.9.1",lastUpdated:"2026.7.15",scheduleUpdated:"2026.7.15"};
function parseCSV(text){const rows=[];let row=[],value="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(value);value=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);value="";if(row.some(v=>v!==""))rows.push(row);row=[]}else value+=c}if(value.length||row.length){row.push(value);rows.push(row)}return rows}
function normalizeDate(value){const raw=String(value||"").trim();if(!raw)return"";let m=raw.match(/^(\d{4})[\/.\-](\d{1,2})[\/.\-](\d{1,2})/);if(m)return`${m[1]}-${String(+m[2]).padStart(2,"0")}-${String(+m[3]).padStart(2,"0")}`;const d=new Date(raw);if(!Number.isNaN(d.getTime()))return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;return""}
function normalizeRows(rows){if(!rows.length)return[];const headers=rows[0].map(h=>h.trim().toLowerCase());return rows.slice(1).map((row,index)=>{const o={};headers.forEach((h,i)=>o[h]=(row[i]||"").trim());const members=(o.members||"").split(/[、,，]/).map(v=>v.trim()).filter(v=>memberOrder.includes(v));return{id:o.id||`row-${index+2}`,date:normalizeDate(o.date),time:o.time||"",category:(o.category||"").toUpperCase(),title:o.title||"",venue:o.venue||"",members,note:o.note||"",url:o.url||"",status:o.status||"公開",addedAt:o.added_at||o.addedat||""}}).filter(e=>e.status!=="非公開"&&e.date&&e.title)}
function normalizeSearch(s){return String(s||"").toLowerCase().normalize("NFKC").replace(/[\s　]+/g,"")}
function addRecurringYonino(list,year,month){const existing=new Set(list.filter(e=>e.category==="YOUTUBE"&&/よにの/.test(e.title)).map(e=>e.date));const last=new Date(year,month+1,0).getDate();for(let d=1;d<=last;d++){const dt=new Date(year,month,d);if(dt.getDay()===0||dt.getDay()===3){const date=`${year}-${String(month+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`;if(!existing.has(date))list.push({id:`yonino-${date}`,date,time:"",category:"YOUTUBE",title:"よにのちゃんねる",venue:"YouTube",members:["菊池風磨"],note:"毎週水曜・日曜更新",url:"",status:"公開",virtual:true})}}}
function getFilteredEvents(){const needle=normalizeSearch(searchText);return events.filter(e=>{const memberOk=selectedMember==="ALL"||e.members.includes(selectedMember);const categoryOk=selectedCategory==="ALL"||e.category===selectedCategory;const hay=normalizeSearch(`${e.title}${e.venue}${e.members.join("")}${e.note}`);return memberOk&&categoryOk&&hay.includes(needle)})}
function renderFilters(){$("memberFilters").innerHTML=[{key:"ALL",label:"すべて",emoji:""},...memberOrder.map(m=>({key:m,label:m,emoji:memberEmoji[m]}))].map(i=>`<button class="chip ${selectedMember===i.key?"active":""}" data-member="${i.key}">${i.emoji?`<span>${i.emoji}</span>`:""}<span>${i.label}</span></button>`).join("");document.querySelectorAll("[data-member]").forEach(b=>b.onclick=()=>{selectedMember=b.dataset.member;localStorage.setItem("timeleszSelectedMember",selectedMember);renderFilters();renderCalendar()});$("categoryFilters").innerHTML=[{key:"ALL",label:"すべて",icon:"layers"},...Object.entries(categories).map(([key,v])=>({key,label:v.label,icon:v.icon}))].map(i=>`<button class="chip ${selectedCategory===i.key?"active":""}" data-category="${i.key}">${icon(i.icon)}<span>${i.label}</span></button>`).join("");document.querySelectorAll("[data-category]").forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.category;renderFilters();renderCalendar()})}
function birthdayInfo(dayEvents,date){const e=dayEvents.find(x=>x.category==="BIRTHDAY");if(!e)return null;const member=e.members[0],cfg=birthdays[member];if(!cfg)return null;return{member,age:+date.slice(0,4)-cfg.year,color:cfg.color}}
function renderCalendar(){const year=shownMonth.getFullYear(),month=shownMonth.getMonth();const source=[...events];addRecurringYonino(source,year,month);const filtered=source.filter(e=>{const memberOk=selectedMember==="ALL"||e.members.includes(selectedMember);const categoryOk=selectedCategory==="ALL"||e.category===selectedCategory;return memberOk&&categoryOk&&normalizeSearch(`${e.title}${e.venue}${e.members.join("")}${e.note}`).includes(normalizeSearch(searchText))});const monthEvents=filtered.filter(e=>{const d=new Date(`${e.date}T00:00:00`);return d.getFullYear()===year&&d.getMonth()===month});$("monthLabel").textContent=`${year}.${month+1}`;const first=new Date(year,month,1).getDay(),last=new Date(year,month+1,0).getDate();let html="";for(let i=0;i<first;i++)html+='<div class="day blank"></div>';for(let day=1;day<=last;day++){const date=`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`,dayEvents=monthEvents.filter(e=>e.date===date),visible=selectedMember==="ALL"?memberOrder.filter(m=>dayEvents.some(e=>e.members.includes(m))):(dayEvents.length?[selectedMember]:[]),bday=birthdayInfo(dayEvents,date),today=new Date(),isToday=today.getFullYear()===year&&today.getMonth()===month&&today.getDate()===day;html+=`<div class="day ${dayEvents.length?"has-events":""} ${isToday?"today":""} ${selectedDate===date?"selected":""} ${bday?`birthday-${bday.color}`:""}" data-date="${date}" role="button" tabindex="0"><div class="day-number">${day}</div>${bday?'<div class="birthday-cake">🎂</div>':""}<div class="member-icons">${visible.map(m=>`<span class="member-emoji">${memberEmoji[m]}</span>`).join("")}</div></div>`}$("calendarGrid").innerHTML=html;document.querySelectorAll(".day:not(.blank)").forEach(c=>{const pick=()=>{selectedDate=c.dataset.date;renderCalendar();if(c.classList.contains("has-events"))openDay(selectedDate,filtered)};c.onclick=pick;c.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();pick()}}});renderCountdown(filtered)}
function renderCountdown(list){const today=new Date();today.setHours(0,0,0,0);const items=list.map(e=>{const d=new Date(`${e.date}T00:00:00`),days=Math.ceil((d-today)/86400000),deadline=/締切|受付終了|予約終了/.test(`${e.title}${e.note}`),release=e.category==="RELEASE";return{e,days,kind:deadline?"deadline":release?"release":""}}).filter(x=>x.kind&&x.days>=0&&x.days<=7).sort((a,b)=>a.days-b.days).slice(0,3);$("countdownList").innerHTML=items.map(x=>`<button class="countdown-item" data-date="${x.e.date}" type="button">${icon(x.kind==="release"?"disc":"clock")}<span class="countdown-title">${x.e.title}</span><span class="countdown-days">${x.days===0?"本日":`あと${x.days}日`}</span></button>`).join("");document.querySelectorAll(".countdown-item").forEach(b=>b.onclick=()=>openDay(b.dataset.date,list))}
function shareText(e){return`${e.title}\n${e.date}${e.time?` ${e.time}`:""}${e.venue?`\n${e.venue}`:""}\n${location.href}`}
async function doShare(type,text=location.href){const url=encodeURIComponent(location.href),encoded=encodeURIComponent(text);if(type==="x")location.href=`https://twitter.com/intent/tweet?text=${encoded}`;else if(type==="line")location.href=`https://line.me/R/msg/text/?${encoded}`;else if(type==="url"){await navigator.clipboard.writeText(location.href);alert("URLをコピーしました") }else if(navigator.share){navigator.share({title:"timelesz Schedule",text,url:location.href}).catch(()=>{})}else{await navigator.clipboard.writeText(text);alert("共有内容をコピーしました")}}
function openDay(date,list=getFilteredEvents()){const dayList=list.filter(e=>e.date===date).sort((a,b)=>(a.time||"99:99").localeCompare(b.time||"99:99")),d=new Date(`${date}T00:00:00`);$("dialogDate").textContent=`${d.getMonth()+1}月${d.getDate()}日`;$("dialogEvents").innerHTML=dayList.map(e=>{const b=e.category==="BIRTHDAY"?birthdayInfo([e],e.date):null;const title=b?`🎂 ${b.age}歳の誕生日`:e.title;return`<article class="event-card"><div class="event-top"><div class="event-icon">${icon(categories[e.category]?.icon||"layers")}</div><div><h3 class="event-title">${title}</h3><div class="event-meta">${e.time?`<span>${icon("clock")}${e.time}〜</span>`:""}${e.venue?`<span>${icon("pin")}${e.venue}</span>`:""}<span>${e.category}</span></div><div class="event-members">${e.members.map(m=>`${memberEmoji[m]}${m}`).join("　")}</div>${e.note?`<p class="event-note">${e.note}</p>`:""}${e.url?`<a class="link-button" href="${e.url}" target="_blank" rel="noopener">${icon(e.category==="YOUTUBE"?"play":"link")}公式ページを見る</a>`:""}<div class="event-share"><button class="social-circle x" data-event-share="x">X</button><button class="social-circle line" data-event-share="line">LINE</button><button class="social-circle instagram" data-event-share="instagram" aria-label="Instagramで共有"></button><button class="social-circle threads" data-event-share="threads" aria-label="Threadsで共有">@</button><button class="social-circle url" data-event-share="url">${icon("link")}</button></div></div></div></article>`}).join("");document.querySelectorAll("[data-event-share]").forEach(b=>b.onclick=()=>doShare(b.dataset.eventShare,shareText(dayList[0])));$("eventDialog").showModal()}
async function fetchCsvByGid(gid){if(!gid)return null;const r=await fetch(`${PUBLISHED_SHEET_BASE}?gid=${gid}&single=true&output=csv&t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(r.status);return parseCSV(await r.text())}
async function loadSiteInfo(){let info={...fallbackSiteInfo};try{const rows=await fetchCsvByGid(SITE_INFO_SHEET_GID);if(rows){rows.slice(1).forEach(r=>{const k=(r[0]||"").trim(),v=(r[1]||"").trim();if(k)info[k]=v})}}catch{}$("siteVersion").textContent=info.version||fallbackSiteInfo.version;$("siteUpdated").textContent=`最終更新日 ${info.lastUpdated||fallbackSiteInfo.lastUpdated}`;$("scheduleUpdated").textContent=info.scheduleUpdated||fallbackSiteInfo.scheduleUpdated}
async function loadHistory(){let history=fallbackHistory;try{const rows=await fetchCsvByGid(HISTORY_SHEET_GID);if(rows){const h=rows[0].map(x=>x.trim().toLowerCase()),groups={};rows.slice(1).forEach(r=>{const o={};h.forEach((k,i)=>o[k]=(r[i]||"").trim());if(!o.version)return;groups[o.version]??={version:o.version,date:o.date||"",changes:[]};if(o.change||o.changes||o["更新内容"])groups[o.version].changes.push(o.change||o.changes||o["更新内容"])});history=Object.values(groups)}}catch{}$("historyList").innerHTML=history.map(h=>`<article class="history-entry"><div class="history-entry-head"><strong>${h.version}</strong><span>${h.date}</span></div><ul class="history-changes">${h.changes.map(c=>`<li>・${c.replace(/^・/,"")}</li>`).join("")}</ul></article>`).join("")}
async function loadEvents(){try{const r=await fetch(`${SHEET_CSV_URL}&t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(r.status);events=normalizeRows(parseCSV(await r.text()));if(!events.length&&Array.isArray(window.FALLBACK_EVENTS))events=window.FALLBACK_EVENTS.map(e=>({...e,date:normalizeDate(e.date)}))}catch{events=Array.isArray(window.FALLBACK_EVENTS)?window.FALLBACK_EVENTS.map(e=>({...e,date:normalizeDate(e.date)})):[]}$("loadingState").classList.add("hidden");renderFilters();renderCalendar();loadSiteInfo();loadHistory()}
$("prevMonth").onclick=()=>{shownMonth=new Date(shownMonth.getFullYear(),shownMonth.getMonth()-1,1);renderCalendar()};$("nextMonth").onclick=()=>{shownMonth=new Date(shownMonth.getFullYear(),shownMonth.getMonth()+1,1);renderCalendar()};$("searchInput").oninput=e=>{searchText=e.target.value;renderCalendar()};$("closeDialog").onclick=()=>$("eventDialog").close();$("eventDialog").onclick=e=>{if(e.target===$("eventDialog"))$("eventDialog").close()};
$("monthJumpBtn").onclick=()=>{const y=$("jumpYear"),m=$("jumpMonth");if(!y.options.length){for(let n=2020;n<=2035;n++)y.add(new Option(n,n));for(let n=1;n<=12;n++)m.add(new Option(`${n}月`,n))}y.value=shownMonth.getFullYear();m.value=shownMonth.getMonth()+1;$("monthJumpDialog").showModal()};$("jumpSubmit").onclick=e=>{e.preventDefault();shownMonth=new Date(+$('jumpYear').value,+$('jumpMonth').value-1,1);$("monthJumpDialog").close();renderCalendar()};
$("shareBtn").onclick=()=>$("shareDialog").showModal();$("closeShare").onclick=()=>$("shareDialog").close();$("closeShareBottom").onclick=()=>$("shareDialog").close();$("shareDialog").onclick=e=>{if(e.target===$("shareDialog"))$("shareDialog").close()};$("historyBtn").onclick=()=>$("historyDialog").showModal();$("closeHistory").onclick=()=>$("historyDialog").close();$("historyDialog").onclick=e=>{if(e.target===$("historyDialog"))$("historyDialog").close()};document.querySelectorAll("[data-share]").forEach(b=>b.onclick=()=>doShare(b.dataset.share));
loadEvents();
